In [265]:
import numpy as np
import pandas as pd

Задание 1

In [266]:
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

In [267]:
b = np.reshape(a,[2,6])
b

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [268]:
b = np.reshape(a,[6,2])
b

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [269]:
c = np.reshape(a,[4,3])
c

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [270]:
d = np.reshape(a,[3,4])
d

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [271]:
e = np.reshape(a,[12,1])
e

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание 3

In [272]:
f = np.reshape(a, (-1,1))
f

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [273]:
g = np.reshape(a, (-1,2))
g

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [274]:
h = np.reshape(a, (-1,3))
h

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [275]:
i = np.reshape(a, (3,-1))
i

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [276]:
j = np.reshape(a, (2,-1))
j

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Задание 4

Нельзя

Задание 5

In [277]:
a = np.random.randn(3,4)
print(a)

[[ 1.46237812  1.53871497 -2.43910582  0.60344123]
 [-0.25104397 -0.16386712 -1.47632969  1.48698096]
 [-0.02445518  0.35555132  0.41701111  0.83246186]]


In [278]:
b = a.ravel()
print(b)
np.size(a) == np.size(b)

[ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397 -0.16386712
 -1.47632969  1.48698096 -0.02445518  0.35555132  0.41701111  0.83246186]


True

Задание 6

In [279]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7

In [280]:
b = np.array([np.arange(20,1,-2)])
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [281]:
print(a.ndim)
print(b.ndim)

1
2


b -  массив двумерный

Задание 8

In [282]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [283]:
b  = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [284]:
c = np.vstack((a,b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [285]:
np.size(c)

10

Задание 9

In [286]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [287]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [288]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [289]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [290]:
np.linalg.det(B)

0.0

Неполучится, определитель равен 0

Задача 10

In [291]:
np.random.seed(42)

In [292]:
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

Задача 11

In [293]:
a = np.arange(0,16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [294]:
np.random.shuffle(a)
a

array([ 0, 10, 15,  1,  8,  5, 11,  3, 14,  7, 13,  2,  9,  6,  4, 12])

Задание 12

In [295]:
C = a.reshape(4,4)
C

array([[ 0, 10, 15,  1],
       [ 8,  5, 11,  3],
       [14,  7, 13,  2],
       [ 9,  6,  4, 12]])

In [296]:
D = C * 10 + B
D

array([[  5, 114, 173,  42],
       [ 94, 100, 196, 152],
       [163, 156, 279, 232],
       [122, 182, 252, 422]])

In [297]:
np.linalg.det(D) # определитель

95676799.99999991

In [298]:
np.linalg.matrix_rank(D) #ранг

4

In [299]:
D_inv = np.linalg.inv(D)  #обратная
D_inv

array([[-0.00462599, -0.02290503,  0.02203209, -0.00340187],
       [ 0.01351362, -0.06701123,  0.0359734 ,  0.00301494],
       [-0.0022229 ,  0.04233294, -0.02225534, -0.00279148],
       [-0.00316336,  0.01024303, -0.00859414,  0.00371982]])

Задание 13

In [300]:
D_inv = (D_inv > 0).astype(int)
D_inv

array([[0, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1]])

In [303]:
E = np.where(D_inv, B, C)
E

array([[  0,  10,  23,   1],
       [ 14,   5,  86, 122],
       [ 14,  86,  13,   2],
       [  9, 122,   4, 302]])