In [92]:
import numpy as np

In [93]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [94]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [95]:
mean_a = a.mean(axis=0)

In [96]:
mean_a

array([2. , 8.4])

In [97]:
a_centered = a - mean_a

In [98]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [102]:
e = a_centered[0:,:1].ravel()
d = a_centered[0:,1:].ravel()
print(e)
print(d)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [103]:
a_centered_sp = e @ d
a_centered_sp / 4

2.0

In [106]:
np.cov(a.T)[0,1]

2.0